server:
  port: 8085
spring:
  application:
    name: shop-cart
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=utf-8&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  rabbitmq:
    port: 5672
    virtual-host: /
    host: 127.0.0.1
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
    publisher-confirm-type: correlated #获取confirm方法
    publisher-returns: true #开启publish-return功能
    template:
      mandatory: true #定义消息路由失败策略，如果设置为false，则直接丢弃消息

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.zhu.pojo

logging:
  level:
    com.zhu.mapper: debug