spring:
  #数据连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=utf-8&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    hikari:
      #连接池名称
      pool-name: myHikari
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间，默认10分钟，这里设置了30分钟
      idle-timeout: 1800000
      #最大连接数，默认是10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0代表永久存活，默认30分钟
      max-lifetime: 1800000
      #连接超时时间，默认30秒
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: select 1
  application:
    name: shop-goods
  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #redis配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  #rabbit配置
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        prefetch: 1
#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.zhu.pojo
  mapper-locations: classpath:/mapper/*Mapper.xml
#输出执行的sql语句
logging:
  level:
    com.zhu.mapper: debug
