spring:
  thymeleaf:
    cache: false
  application:
    name: shop-seckill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=utf-8&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  rabbitmq:
    port: 5672
    virtual-host: /
    host: 127.0.0.1
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1

server:
  port: 8087